### PR TITLE
[FIX] travis2docker: Fix --remotes parameter not support gitlab or other domain

### PR DESCRIPTION
**Pull request by JesusZapata**
Fix https://github.com/Vauxoo/runbot-addons/issues/92

To reproduce the error
```bash
travisfile2dockerfile --add-remote=vauxoo,vauxoo-dev git@gitlab.com:Group/repo.git master
```

### CODE REVIEW

**Comment by JesusZapata** [comment]
@moylop260 
What do you think about this pull request?

**Comment by moylop260** [comment]
@zaoral 
Could you help us to test it?

**Comment by moylop260** [comment]
@JesusZapata 
What about use [git_run](https://github.com/Vauxoo/travis2docker/blob/master/src/travis2docker/git_run.py#L29-L31) script where the url is separated by item host, owner and repo in order to replace the owner by the parameter added from `add-remote`?

**Comment by JesusZapata** [comment]
@moylop260 
What do you think of last commit?

**Comment by zaoral** [comment]
> @zaoral
> Could you help us to test it?

Hi @moylop260 @JesusZapata 
Sure I will test it.
Let you now soon the results.

Best Regards

**Comment by zaoral** [comment]
Hi @moylop260  and @JesusZapata 

I just make the test, this are the results:

- now the container is created using the branch for gitlab
- however the two remotes vauxoo and vauxoo-dev are there, but they refer to github instead of gitlab as you can see in the next screenshot
 image

Do you think is a good idea, and if it is possible, to be able to have this remotes like the next form?

```diff
origin  git@git.vauxoo.com:Vauxoo/instance.git (fetch)
origin  git@git.vauxoo.com:Vauxoo/instance.git (push)
- vauxoo  git@github.com:vauxoo/instance.git (fetch)
- vauxoo  git@github.com:vauxoo/instance.git (push)
+ vauxoo  git@git.vauxoo.com:vauxoo/instance.git (fetch)
+ vauxoo  git@git.vauxoo.com:vauxoo/instance.git (push)
- vauxoo-dev      git@github.com:vauxoo-dev/instance.git (fetch)
- vauxoo-dev      git@github.com:vauxoo-dev/instance.git (push)
+ vauxoo-dev      git@git.vauxoo.com:vauxoo-dev/instance.git (fetch)
+ vauxoo-dev      git@git.vauxoo.com:vauxoo-dev/instance.git (push)
```

**Comment by moylop260** [comment]
What is the `travisfile2dockerfile --version`

if version < `travisfile2dockerfile 3.3.2` then upgrade it, please `pip install -U travis2docker`

I used:
```bash
t2d git@git.vauxoo.com:vauxoo/instance.git 10.0
cat Dockerfile | grep remote
    && git remote add origin git@git.vauxoo.com:vauxoo/instance.git \
    && git remote add vauxoo git@git.vauxoo.com:vauxoo/instance.git \
    && git remote add vauxoo-dev git@git.vauxoo.com:vauxoo-dev/instance.git \
```

And is using git.vauxoo.com host

**Pull request merged**
