### PR TITLE
[ADD] Dockerfile: Support for RVM

### PR DESCRIPTION
**Pull request by lasley**
As noted in Vauxoo/docker-odoo-image#165

* Add bash encapsulation & sourcing for install commands
* Add RVM source to entrypoint

### CODE REVIEW

**Comment by lasley** [comment]
Alright we have ourselves a universal RVM handler. Cases covered are the travis, the known odoo, and any unknown image that possibly doesn't have RVM at all.

**Comment by moylop260** [comment]
Thanks!

We need copy the new `templates/rvm_env.sh` to `files/rvm_env.sh`

Steps to reproduce a fail by this reason:
1. Run `travisfile2dockerfile --exclude-after-success --docker-image=quay.io/travisci/travis-python --docker-user=travis git@github.com:OCA/website.git pull/284`
2. Run the 10-build.sh script.

Saw:
```bash
Step 1 : FROM quay.io/travisci/travis-python
 ---> 753a216d776c
Step 2 : ADD files/entrypoint.sh /entrypoint.sh
 ---> 321d778b2028
Removing intermediate container 67ecbfb7ceaa
Step 3 : RUN chown -R travis:travis /entrypoint.sh
 ---> Running in 6aa9103620dd
 ---> cd0caa1091bd
Removing intermediate container 6aa9103620dd
Step 4 : ADD files/rvm_env.sh /rvm_env.sh
lstat files/rvm_env.sh: no such file or directory
```

**Comment by moylop260** [comment]
Now, using our image works fine!
screen shot 2016-11-21 at 5 48 41 pm

But using original travis image fail
screen shot 2016-11-21 at 5 49 51 pm

screen shot 2016-11-21 at 5 50 25 pm

This is because we are running the install script from `root`.
But is unrelated...

Thanks!

**Comment by lasley** [comment]
💥 !

**Pull request merged**
