### PR TITLE
[IMP] Add authorized_keys

### PR DESCRIPTION
**Pull request by osvalr**
This change adds public ssh key as authorized keys including `id_rsa.pub` key.

This is handy for `ssh` (of course) and when using `mosh`

Thanks @hbto for the hint

Demo:
[](https://asciinema.org/a/0n09jwlglh0hkhxgqme79arza)

### CODE REVIEW

**Comment by moylop260** [comment]
@osvalr 
I'm agree of add our public key to `authorized_keys`... but what about if we have a `authorized_keys` with other values (myComputer1, myComputer2...)
Should we use original values?
or Should we use just my current public key?
What do you think?

**Comment by nhomar** [comment]
:-1: 

No está bien que por defectu un docker tenga acceso a tus privates keys, adicional este comando requeriría un chmod sino la conexión ssh te quedará incompleta.

Ojo con eso.

**Comment by osvalr** [comment]
@nhomar son las llaves públicas, y es sólo un enlace simbólico

**Comment by moylop260** [comment]
@nhomar 
This change is to add a `public` key (no private key)

**Comment by osvalr** [comment]
@moylop260 indeed this proposal uses the public ones inside the docker that is actually the used ones

**Comment by osvalr** [comment]
@moylop260 that's the main why it is just a symlink

**Comment by moylop260** [comment]
@osvalr 
I'm talking about follow case:

Currently I have 3 keys in `~/.ssh/authorized_keys`
 - Key1
 - Key2
 - Key3
If I execute:
`ln -sf ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys"`
I will have 1 key in `~/.ssh/authorized_keys`
  - MyOwnKey

What about other keys?
`runbot_travis2docker` use other keys to allow connect to ssh in docker build to all our users, then with this change we will have a deny connection to runbot.

Do you can concatenate the current public key to current authorized_keys?

**Comment by osvalr** [comment]
@moylop260 appending the `>>` to `authorized_keys`?

**Comment by moylop260** [comment]
Yes, appending

**Comment by moylop260** [comment]
FYI I had a random issue in the past with `>>`  in docker.
Mayber you could use: `tee -a...`

**Comment by osvalr** [comment]
the only thing annoying is that there is no quiet mode for `tee` command

**Comment by moylop260** [comment]
In t2d I have a tee command...
Can you check it?

**Comment by osvalr** [comment]
the only tee command applied seems to be at [205](https://github.com/Vauxoo/travis2docker/blob/master/travis2docker/travis2docker.py#L205), am I missing something?

**Comment by moylop260** [comment]
Yep

**Comment by osvalr** [comment]
@moylop260 I've added a little demo proving this with the image already generated

**Comment by moylop260** [comment]
@nhomar 
This PR don't change the current behaviour to manage keys in container...
We can discuss in other PR the matter manage of keys.

For now, we can merge this PR.

**Pull request merged**
