### PR TITLE
[REF] .travis.yml,etc: Deprecate Python 2.7 & 3.4

### PR DESCRIPTION
**Pull request by luisg123v**
Support for those versions has been officially dropped, which causes issues
when dependencies are installed.

### CODE REVIEW

**Comment by luisg123v** [comment]
@moylop260 what do you think?

**Comment by moylop260** [comment]
What is the rational to do this?
I mean, I didn't see an improvement removing old python versions
And the current code works for all versions

**Comment by luisg123v** [comment]
@moylop260 current stable branch is red because some Python 2 dependencies can't be installed anymore

**Comment by moylop260** [comment]
What about using requirements.txt with pinning the package version based on python version.

Similar to:
https://github.com/odoo/odoo/pull/25841

I mean, We are using just 2 libraries.

The last stable travis build installed the following versions:

```txt
py27 installed: atomicwrites==1.3.0,attrs==19.2.0,configparser==4.0.2,contextlib2==0.6.0.post1,coverage==4.5.4,funcsigs==1.0.2,importlib-metadata==0.23,Jinja2==2.10.3,MarkupSafe==1.1.1,more-itertools==5.0.0,nodeenv==1.3.3,packaging==19.2,pathlib2==2.3.5,pluggy==0.13.0,py==1.8.0,pyparsing==2.4.2,pytest==4.6.5,pytest-cov==2.8.1,pytest-travis-fold==1.3.0,PyYAML==5.1.2,scandir==1.10.0,six==1.12.0,travis2docker==5.1.1,wcwidth==0.1.7,whichcraft==0.6.1,zipp==0.6.0
```

**Comment by luisg123v** [comment]
@moylop260 I like the idea.

On the other hand, some of the builds is still failing because of a checker. Could you have a look to it, please? I'm sure you're familiar to it.

```
/home/travis/build/Vauxoo/travis2docker$ /home/travis/build/Vauxoo/travis2docker/.tox/check/bin/check-manifest .
lists of files in version control and sdist do not match!
missing from VCS:
  src/travis2docker/travis-ci-apt-source-whitelist/.git
ERROR: InvocationError for command /home/travis/build/Vauxoo/travis2docker/.tox/check/bin/check-manifest . (exited with code 1)
```

**Comment by moylop260** [comment]
@luisg123v 
Superseded by https://github.com/Vauxoo/travis2docker/pull/132

**Pull request closed without merging**
