### PR TITLE
Add no-cache, include-cleanup, and remove-after-success CLI args

### PR DESCRIPTION
**Pull request by lasley**
Hi Friends!

Thanks for the excellent app, it has really helped us integrate our existing CI into the Odoo testing workflow. 

We did have to add a few CLI args to make it work for our purposes; figured you may want them as well:

* `--remove-after-success` - Hard codes a removal of the `after_success` section - we use in-house coverage solution, so needed this to be explicitly removed to keep from coveralls from generating errors
* `--include-cleanup` - Injects image removal into Docker run script in order to save space
* `--no-cache` - Injects `--no-cache` into Docker build script in order to eliminate stale builds

I basically learned Docker with this project, so if you have a better solution to something I did here, I'm all ears :smile:

### CODE REVIEW

**Comment by moylop260** [comment]
@lasley 
Thank for contribution and your words.

- `remove-after-success`
I have created a new issue for the case of `after-success`
https://github.com/Vauxoo/travis2docker/issues/36
Should be optional as you good told us.
Currently exists the parameter `--include-after-success` but I saw that don't work correctly.
We will fix it.

- `include-cleanup`
:+1:

- `--no-cache`
We can add a new parameter similar to `--run-extra-args` but for `--build-extra-args` to add:
 - `--no-cache`
 - `--pull`
 - `-q`
 - and so on.

I will work in `remove-after-success`

If you can help me could remove the feature `remove-after-success` and work with the `include-cleanup` and `--build-extra-args`.

Thanks a lot

**Comment by moylop260** [comment]
@lasley 
FYI Check follow module: https://github.com/Vauxoo/runbot-addons/tree/9.0/runbot_travis2docker

**Comment by lasley** [comment]
@moylop260 

Thanks for the explanation. Hah I tried for a while to get the existing `after-success` flag to work for me, but failed miserably. Makes sense it was broken!

Good call with the build params, my bad for missing that. Will get both points updated within the hour.

Thanks for the Runbot addon as well - we have already implemented it in our Runbot & it is running like a champ!

These additions were actually to get everything integrated with Jenkins/Bamboo, which is our equivalent of Travis. We had to add some XMLRunner/Coverage.py injections to your Docker build in order to get things to work as well (thanks for that too). This is a description of what we rigged up - https://blog.laslabs.com/2016/02/using-bamboo-to-test-odoo-ubuntu/

**Comment by lasley** [comment]
@moylop260 Should be good to go now. I really like the `docker-extra-args` idea - way more abstract than mine!

**Comment by moylop260** [comment]
Thank you!

Your blog is very good and useful!
Thank you!

**Pull request merged**
