### PR TITLE
[ADD] Adding sleep 2 to file script file fixed #86

### LINKED ISSUE #86: Add a `sleep 5` at final of `script` section
History
=====

Currently we have from `.travis.yml` file the following data:
```yml
...
script:
    - travis_run_tests
...
```

And we have a postgresql configured with [non-durability](https://www.postgresql.org/docs/9.3/static/non-durability.html) from [vauxoo/odoo-80-image-shippable-auto](https://hub.docker.com/r/vauxoo/odoo-80-image-shippable-auto/) image.
This parameter generate a postgtresql faster but if the docker is stoped before of a checkpoint then the last transaction is deleted.

Runbot after run `travis_run_tests` command stop the container.

These combinations create the requirement of add a `sleep 2` command from travis2docker in order to wait a checkpoint from postgresql database.
Because currently we are adding it for each `.travis.yml` file, but is not the ideal deal.
Better centralize the parameter from travis2docker.

Requirement
=========

Add a hardcoded `sleep 2` at final of `script` section from jinja template

### PR DESCRIPTION
**Pull request by JesusZapata**
fixed #86

### CODE REVIEW

**Comment by JesusZapata** [comment]
@moylop260 
This is a good solution?

**Comment by JesusZapata** [comment]
@moylop260 
The appveyor is in red, but i can see another's build y all is in red.

**Comment by moylop260** [comment]
Could you add a sample image where the final result is showed?

**Comment by JesusZapata** [comment]
@moylop260 
image

**Pull request merged**
